name: Sync Image to Aliyun  Example

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Git pull
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2.9.1

    - name: Login to Docker Hub
      uses: docker/login-action@v2.2.0
      with:
        registry: registry.cn-hangzhou.aliyuncs.com
        username: "${{ secrets.ALIYUN_REGISTRY_USER }}"
        password: "${{ secrets.ALIYUN_REGISTRY_PASSWORD }}"  
        logout: false

    - name: Use Skopeo Tools Sync Image to Docker Hub
      run: |
         skopeo copy docker://docker.io/portainer/portainer-ce@sha256:4f6f585b813dc72e84f0780b2fca6531bdb1d12f3c67e95056e2e159fb0d384a docker://registry.cn-hangzhou.aliyuncs.com/study_zyj/portainer
         

